# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ffi-libelf}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Postmodern"]
  s.date = %q{2010-02-16}
  s.description = %q{}
  s.email = %q{postmodern.mod3@gmail.com}
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".gitignore",
    ".specopts",
    ".yardopts",
    "ChangeLog.md",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/elf.rb",
    "lib/elf/32/aux_vec.rb",
    "lib/elf/32/dyn.rb",
    "lib/elf/32/file_header.rb",
    "lib/elf/32/lib.rb",
    "lib/elf/32/m68k.rb",
    "lib/elf/32/move.rb",
    "lib/elf/32/note_header.rb",
    "lib/elf/32/program_header.rb",
    "lib/elf/32/rel.rb",
    "lib/elf/32/rel_addend.rb",
    "lib/elf/32/section_header.rb",
    "lib/elf/32/sym.rb",
    "lib/elf/32/sym_info.rb",
    "lib/elf/32/typedefs.rb",
    "lib/elf/32/ver_def.rb",
    "lib/elf/32/ver_def_aux.rb",
    "lib/elf/32/ver_need.rb",
    "lib/elf/32/ver_need_aux.rb",
    "lib/elf/64/aux_vec.rb",
    "lib/elf/64/dyn.rb",
    "lib/elf/64/file_header.rb",
    "lib/elf/64/lib.rb",
    "lib/elf/64/move.rb",
    "lib/elf/64/note_header.rb",
    "lib/elf/64/program_header.rb",
    "lib/elf/64/rel.rb",
    "lib/elf/64/rel_addend.rb",
    "lib/elf/64/section_header.rb",
    "lib/elf/64/sym.rb",
    "lib/elf/64/sym_info.rb",
    "lib/elf/64/typedefs.rb",
    "lib/elf/64/ver_def.rb",
    "lib/elf/64/ver_def_aux.rb",
    "lib/elf/64/ver_need.rb",
    "lib/elf/64/ver_need_aux.rb",
    "lib/elf/archive_header.rb",
    "lib/elf/archive_symbol.rb",
    "lib/elf/aux_vec.rb",
    "lib/elf/commands.rb",
    "lib/elf/data.rb",
    "lib/elf/dyn.rb",
    "lib/elf/ffi.rb",
    "lib/elf/file_header.rb",
    "lib/elf/file_types.rb",
    "lib/elf/flags.rb",
    "lib/elf/lib.rb",
    "lib/elf/m64k.rb",
    "lib/elf/move.rb",
    "lib/elf/note_header.rb",
    "lib/elf/program_header.rb",
    "lib/elf/rel.rb",
    "lib/elf/rel_addend.rb",
    "lib/elf/section_header.rb",
    "lib/elf/sym.rb",
    "lib/elf/sym_info.rb",
    "lib/elf/typedefs.rb",
    "lib/elf/types.rb",
    "lib/elf/ver_def.rb",
    "lib/elf/ver_def_aux.rb",
    "lib/elf/ver_need.rb",
    "lib/elf/ver_need_aux.rb",
    "lib/elf/version.rb",
    "spec/libelf_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://github.com/postmodern/ffi-libelf}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{FFI bindings to libelf.}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/libelf_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0.6.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<yard>, [">= 0.5.3"])
    else
      s.add_dependency(%q<ffi>, [">= 0.6.0"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<yard>, [">= 0.5.3"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0.6.0"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<yard>, [">= 0.5.3"])
  end
end

