module FFI
  module Elf
    #
    # Known translation types.
    #
    ELF_T_BYTE = 0                # unsigned char
    ELF_T_ADDR = 1                # Elf32_Addr, Elf64_Addr, ...
    ELF_T_DYN = 2                 # Dynamic section record.
    ELF_T_EHDR = 3                # ELF header.
    ELF_T_HALF = 4                # Elf32_Half, Elf64_Half, ...
    ELF_T_OFF = 5                 # Elf32_Off, Elf64_Off, ...
    ELF_T_PHDR = 6                # Program header.
    ELF_T_RELA = 7                # Relocation entry with addend.
    ELF_T_REL = 8                 # Relocation entry.
    ELF_T_SHDR = 9                # Section header.
    ELF_T_SWORD = 10              # Elf32_Sword, Elf64_Sword, ...
    ELF_T_SYM = 11                # Symbol record.
    ELF_T_WORD = 12               # Elf32_Word, Elf64_Word, ...
    ELF_T_XWORD = 13              # Elf32_Xword, Elf64_Xword, ...
    ELF_T_SXWORD = 14             # Elf32_Sxword, Elf64_Sxword, ...
    ELF_T_VDEF = 15               # Elf32_Verdef, Elf64_Verdef, ...
    ELF_T_VDAUX = 16              # Elf32_Verdaux, Elf64_Verdaux, ...
    ELF_T_VNEED = 17              # Elf32_Verneed, Elf64_Verneed, ...
    ELF_T_VNAUX = 18              # Elf32_Vernaux, Elf64_Vernaux, ...
    ELF_T_NHDR = 19               # Elf32_Nhdr, Elf64_Nhdr, ...
    ELF_T_SYMINFO = 20 		        # Elf32_Syminfo, Elf64_Syminfo, ...
    ELF_T_MOVE = 21               # Elf32_Move, Elf64_Move, ...
    ELF_T_LIB = 22                # Elf32_Lib, Elf64_Lib, ...
    ELF_T_GNUHASH = 23            # GNU-style hash section.
    ELF_T_AUXV = 24               # Elf32_auxv_t, Elf64_auxv_t, ...
    ELF_T_NUM = 25
  end
end
